Student.Web/Controllers/CustomAccountController.cs
using Student.Library;
using Student.Library.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace Student.Web.Controllers
{
    [AllowAnonymous]
    public class CustomAccountController : Controller
    {
        private UsersDAL _usersDAL;

        public CustomAccountController()
        {
            this._usersDAL = new UsersDAL();
        }

        //
        // GET: /CustomAccount/

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            user=_usersDAL.GetUser(user.UserName, user.PassWord);
            if(user==null)
            {
                ViewBag.errorMsg = "Invalid User";
                return View();
            }
            else
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                return RedirectToAction("Index", "Students");
            } 
        }

        // POST: /Account/LogOff

        [HttpPost]        
        public ActionResult LogOut()
        {
            WebSecurity.Logout();
            return RedirectToAction("Index", "Students");
        }

    }
}

Student.Web/Views/CustomAccount/Login.cshtml
@model Student.Library.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Custom Login</h2>

@using (Html.BeginForm("Login","CustomAccount",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @ViewBag.errorMsg
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PassWord)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PassWord)
            @Html.ValidationMessageFor(model => model.PassWord)
        </div>
        <p>
            <input type="submit" value="Login" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}